CREATE TABLE customer
(
    ID          INT(11) NOT NULL AUTO_INCREMENT,
    EMAIL       VARCHAR(127) NOT NULL UNIQUE,
    FIRST_NAME  VARCHAR(127) NOT NULL,
    LAST_NAME   VARCHAR(127) NOT NULL,
    AGE         INT(11),
    SEARCH_NAME VARCHAR(255) NOT NULL,
    VERSION     INT(11),
    PRIMARY KEY (ID)
);
